# vim: syntax=python
#

rule step1:
    input:
        "/data1/input/haha"
    output:
        "/data1/out/lala"
    shell:
        """
        cat /data1/input/haha /data1/input/haha > /data1/out/lala
        """

rule step2:
    input:
        "/data1/input/lala"
    output:
        "/data1/out/lalala"
    shell:
        """
        cat /data1/input/lala /data1/input/lala > /data1/out/lalala
        """

rule step3:
    input:
        "/data1/input/lalala"
    output:
        "/data1/out/lalalala"
    shell:
        """
        cat /data1/input/lalala /data1/input/lalala > /data1/out/lalalala
        """

