region: us-east-1

function_name: export_files_sbg 
handler: service.handler
role: lambda_full_s3
description: Once a task is complete, export the files to the appropriate S3 

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 300 
memory_size: 128 
