region: us-east-1

function_name: check_task_awsem
handler: service.handler
role: tibanna_lambda_init_role
description: check status of AWSEM run by interegating appropriate files on S3 

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 300 
memory_size: 256
runtime: python3.6
