#!/bin/bash

cd /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/tmp.c6637eb4" && echo "/cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/tmp.c6637eb4")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution

)
outa8315bfa="${tmpDir}/out.$$" erra8315bfa="${tmpDir}/err.$$"
mkfifo "$outa8315bfa" "$erra8315bfa"
trap 'rm "$outa8315bfa" "$erra8315bfa"' EXIT
tee '/cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/stdout' < "$outa8315bfa" &
tee '/cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/stderr' < "$erra8315bfa" >&2 &
(
cd /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution


python $(which encode_macs2_atac.py) \
	/cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/inputs/609996275/4DNFIUZBIYW9.tagAlign.gz \
	--gensz hs \
	--chrsz /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/inputs/-1873131033/4DNFIZJB62D1.chrom.sizes \
	--cap-num-peak 300000 \
	--pval-thresh 0.01 \
	--smooth-win 150 \
	--make-signal \
	--blacklist /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/inputs/1792182009/4DNFIZ1TGJZR.bed.gz

# ugly part to deal with optional outputs with Google JES backend

touch null
)  > "$outa8315bfa" 2> "$erra8315bfa"
echo $? > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution
sync
# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-254907fcd430d7e6c9bf67ac4585adb4

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-254907fcd430d7e6c9bf67ac4585adb4/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*[!.][!b][!f][!i][!l][!t].narrowPeak.gz /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-254907fcd430d7e6c9bf67ac4585adb4 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*[!.][!b][!f][!i][!l][!t].narrowPeak.gz /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-254907fcd430d7e6c9bf67ac4585adb4 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-254907fcd430d7e6c9bf67ac4585adb4 | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-254907fcd430d7e6c9bf67ac4585adb4.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-2e6c87fc90e45fa5dbda88934d454cd3

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-2e6c87fc90e45fa5dbda88934d454cd3/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.bfilt.narrowPeak.gz /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-2e6c87fc90e45fa5dbda88934d454cd3 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.bfilt.narrowPeak.gz /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-2e6c87fc90e45fa5dbda88934d454cd3 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-2e6c87fc90e45fa5dbda88934d454cd3 | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-2e6c87fc90e45fa5dbda88934d454cd3.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-155eada107f68a2195912a39f5dee4bc

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-155eada107f68a2195912a39f5dee4bc/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.bfilt.narrowPeak.bb /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-155eada107f68a2195912a39f5dee4bc 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.bfilt.narrowPeak.bb /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-155eada107f68a2195912a39f5dee4bc )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-155eada107f68a2195912a39f5dee4bc | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-155eada107f68a2195912a39f5dee4bc.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-08ed81b9c4c9ccf6c3692d9ea29b11e0

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-08ed81b9c4c9ccf6c3692d9ea29b11e0/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.bfilt.narrowPeak.hammock.gz* /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-08ed81b9c4c9ccf6c3692d9ea29b11e0 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.bfilt.narrowPeak.hammock.gz* /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-08ed81b9c4c9ccf6c3692d9ea29b11e0 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-08ed81b9c4c9ccf6c3692d9ea29b11e0 | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-08ed81b9c4c9ccf6c3692d9ea29b11e0.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-7ab0340dfeb10ca109917cbdcc568548

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-7ab0340dfeb10ca109917cbdcc568548/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.pval.signal.bigwig /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-7ab0340dfeb10ca109917cbdcc568548 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.pval.signal.bigwig /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-7ab0340dfeb10ca109917cbdcc568548 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-7ab0340dfeb10ca109917cbdcc568548 | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-7ab0340dfeb10ca109917cbdcc568548.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/null /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/null /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-8876d8ced974dc46a0c7a4fac20a3a95

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-8876d8ced974dc46a0c7a4fac20a3a95/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.fc.signal.bigwig /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-8876d8ced974dc46a0c7a4fac20a3a95 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.fc.signal.bigwig /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-8876d8ced974dc46a0c7a4fac20a3a95 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-8876d8ced974dc46a0c7a4fac20a3a95 | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-8876d8ced974dc46a0c7a4fac20a3a95.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/null /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/null /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd.list

# make the directory which will keep the matching files
mkdir /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-156b027b56a0fc9230201b265d9f4bf4

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-156b027b56a0fc9230201b265d9f4bf4/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.frip.qc /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-156b027b56a0fc9230201b265d9f4bf4 2> /dev/null ) || ( ln /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/*.frip.qc /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-156b027b56a0fc9230201b265d9f4bf4 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-156b027b56a0fc9230201b265d9f4bf4 | grep -v cromwell_glob_control_file > /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/glob-156b027b56a0fc9230201b265d9f4bf4.list


)
mv /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/rc.tmp /cromwell-executions/atac/a8315bfa-7765-49c6-a824-8e524fbfb28d/call-macs2/shard-0/execution/rc
