region: us-east-1

function_name: validate_md5_s3_trigger_dev 
handler: service.handler
role: lambda_s3_step_function 
description: when file uploaded to s3 bucket, trigger validate_md5 workflow run 

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 60 
memory_size: 128 
runtime: python3.6
